### ISSUE TITLE
Pattern sewing instructions?

### ISSUE THREAD

**Issue by altsalt** [HummingbirdHammocks/ultralight-hammocks#3]
Hello, I have been following these designs for some time and am finally considering sewing one up myself out of non-lightweight materials for pre-modern festivals. However, I don't see any instructions in this repository akin to the ones [available for the mega hammock](https://github.com/HummingbirdHammocks/specialty-hammocks/tree/master/Mega). The response to #2 suggests that you won't be releasing these, but I figured as that was last year, it was worth checking again. However, if you won't be releasing them, would the instructions given for the mega generally be a good place to start? Are there any examples of how you suggest sewing up the ends for a strong connection? Thanks much for being an Open Hardware supporter!

**Comment by loidolt** [comment]
Hi, 

Thank you for following our designs and reaching out! I'm coming around to the idea of writing proper instructions, but it will take me a while to complete that either way. 

In the meantime, the sewing is essentially the same as any other gathered end/ channel end hammock. This video seems to do a decent job showing how to sew one: [https://www.youtube.com/watch?v=4mg7TVhqNmQ](https://www.youtube.com/watch?v=4mg7TVhqNmQ).

The button links are slightly complex to make and sew, you would also need our custom nylon buttons. I recommend just ordering a set from us ([Replacement Button Link Set](https://hummingbirdhammocks.com/products/replacement-button-link-set)) or using an alternative method.

Be sure to use fabric and thread that is appropriate for the job. Size E bonded nylon thread thread will be sufficient and is reasonably easy to tension correctly in a home sewing machine.

**Comment by altsalt** [comment]
In terms of fabric, I was actually contemplating using a canvas drop-cloth as the goal is to make a hammock that won't look out of place at a renaissance faire. I'm a bit confused about how the button system works. Does it feed through the end slots like a whoopie-sling and act like a carabiner?

Thank you for the links and further consideration for releasing instructions!

**Comment by loidolt** [comment]
If you are using canvas you will need to adjust your stitching and thread choices to accommodate that fabric. I'm not very familiar with canvas and it's best practices so I can't really make any recommendations.

The button links serve to provide an attachment point to the gathered end of the hammock as well as carabiner type functionality. Your description is essentially accurate if you were to use an integrated whoopie sling hammock system. However, our button links will almost certainly not fit through the gathered end of a canvas hammock due to the extra bulk.

This guide from The Ultimate Hang provides some great examples of different attachment methods: [https://theultimatehang.com/2013/10/29/make-hammock-3-minutes/](https://theultimatehang.com/2013/10/29/make-hammock-3-minutes/)

**Comment by altsalt** [comment]
Thanks!
